model:
  base_learning_rate: 5.0e-05
  target: src.modules.ldm.latentdiffusion.LatentDiffusion
  params:
    linear_start: 0.00085
    linear_end: 0.012
    num_timesteps_cond: 1
    log_every_t: 200
    timesteps: 1000
    first_stage_key: image
    cond_stage_key: caption
    image_size: 512
    channels: 4
    cond_stage_trainable: true
    conditioning_key: crossattn
    monitor: val/loss_simple_ema
    scale_factor: 0.18215
    use_ema: false

    unet_config:
      target: src.modules.diffusionmodules.unet.UNetModel
      params:
        image_size: 512
        in_channels: 4
        out_channels: 4
        model_channels: 320
        attention_resolutions:
          - 4
          - 2
          - 1
        num_res_blocks: 2
        channel_mult:
          - 1
          - 2
          - 4
          - 4
        num_head_channels: 8
        use_spatial_transformer: true
        transformer_depth: 1
        context_dim: 1280
        use_checkpoint: true
        legacy: false

    first_stage_config:
      target: src.modules.encoders.VQModelInterface
      params:
        num_embeddings: 8192
        embedding_dim: 4
        ddconfig:
          double_z: true
          z_channels: 4
          resolution: 512
          in_channels: 3
          out_ch: 3
          ch: 128
          ch_mult:
            - 1
            - 2
            - 4
            - 4
          num_res_blocks: 2
          attn_resolutions: [ ]
          dropout: 0.0
        lossconfig:
          target: torch.nn.Identity
    cond_stage_config:
      target: ldm.modules.encoders.textembedder.ClipTextEmbedder
      params:
        n_embed: 640
        n_layer: 32
